#!/usr/bin/env python3
"""Build DNA with a chosen set of modules.

A profile names the modules for each slot (keymaps, frontends, explorers,
pickers). Dyn has no conditional compilation, so the build stages a copy of
src/ without the files of modules left out, puts small stubs in their place
(modules/stubs/), and writes build_profile.dyn listing what is included.

Usage: profile.py NAME [MODE]      (profiles/NAME.toml or ~/.config/dna/profiles/NAME.toml)
       profile.py --keymaps helix,vim --frontends gui [--name custom] [MODE]
"""
import os
from pathlib import Path
import shutil
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'scripts'))
from runpath import runpath  # noqa: E402

# Every module, its source files under src/, and stubs for files that other
# code calls into. Modules without files are part of the shared core today.
SLOTS = {
    'keymaps': {'helix': [], 'vim': ['vim.dyn']},
    'frontends': {'gui': ['platform/sdl.dyn', 'text/ttf.dyn'], 'tui': []},
    'explorers': {'buffer': [], 'tree': ['tree_explorer.dyn']},
    'pickers': {'full': [], 'compact': ['picker_compact.dyn'], 'dropdown': ['picker_dropdown.dyn']},
}
REQUIRED = {'keymaps': 'helix', 'frontends': None, 'explorers': 'buffer', 'pickers': 'full'}
STUBS = {name: f'modules/stubs/{name}' for name in ('vim.dyn', 'tree_explorer.dyn', 'picker_compact.dyn', 'picker_dropdown.dyn')}


# Backend files that only declare foreign functions. Without their module,
# each declaration becomes a Dyn function returning a neutral value, so the
# wrappers still compile and nothing links the foreign library. The terminal
# frontend never reaches them; init-style calls report success.
GENERATED = {'platform/sdl.dyn', 'text/ttf.dyn'}
SUCCEEDS = {'init'}


def backend_stub(source):
    import re
    lines = ['// Generated by scripts/profile.py: this build leaves the GUI out.']
    for line in source.splitlines():
        match = re.match(r'^(pub )?extern fn (\w+) "\w+"\((.*)\)\s*(.*)$', line)
        if not match:
            continue
        public, name, parameters, result = match.groups()
        result = result.strip()
        if not result:
            body = ''
        elif result == 'bool':
            body = '  return true\n' if name in SUCCEEDS else '  return false\n'
        elif result == 'rawptr' or result.startswith('*'):
            body = '  return nil\n'
        elif result == 'f32':
            body = '  return 0.0\n'
        else:
            body = '  return 0\n'
        returns = f' {result}' if result else ''
        lines.append(f'{public or ""}fn {name}({parameters}){returns} {{\n{body}}}')
    return '\n'.join(lines) + '\n'


def load(name):
    for directory in (ROOT / 'profiles', Path(os.environ.get('XDG_CONFIG_HOME', Path.home() / '.config')) / 'dna/profiles'):
        path = directory / f'{name}.toml'
        if path.is_file():
            chosen = {}
            for line in path.read_text().splitlines():
                line = line.split('#', 1)[0].strip()
                if not line:
                    continue
                key, _, value = line.partition('=')
                key, value = key.strip(), value.strip()
                if key not in SLOTS or not (value.startswith('[') and value.endswith(']')):
                    raise SystemExit(f'{path}: expected slot = ["module", ...] lines, got: {line}')
                chosen[key] = [item.strip().strip('"') for item in value[1:-1].split(',') if item.strip()]
            return chosen
    raise SystemExit(f'No profile {name!r} in profiles/ or ~/.config/dna/profiles/.')


def main():
    arguments = sys.argv[1:]
    chosen, name, mode = {}, None, 'release'
    while arguments:
        item = arguments.pop(0)
        if item.startswith('--') and item[2:] in SLOTS:
            chosen[item[2:]] = [value for value in arguments.pop(0).split(',') if value]
        elif item == '--name':
            name = arguments.pop(0)
        elif item in ('debug', 'release'):
            mode = item
        elif name is None and not chosen:
            name = item
            chosen = load(item)
        else:
            raise SystemExit(__doc__)
    name = name or 'custom'
    for slot, modules in SLOTS.items():
        selected = chosen.get(slot, list(modules))
        for module in selected:
            if module not in modules:
                raise SystemExit(f'Unknown {slot[:-1]} module {module!r}; known: {", ".join(modules)}.')
        if REQUIRED[slot] is None and not selected:
            raise SystemExit(f'At least one of {", ".join(modules)} is required in {slot}.')
        if REQUIRED[slot] is not None and REQUIRED[slot] not in selected:
            raise SystemExit(f'{REQUIRED[slot]!r} is required in {slot} for now; it is the shared base.')
        chosen[slot] = selected
    stage = ROOT / 'build' / f'profile-{name}'
    if stage.exists():
        shutil.rmtree(stage)
    shutil.copytree(ROOT / 'src', stage)
    for slot, modules in SLOTS.items():
        for module, sources in modules.items():
            if module in chosen[slot]:
                continue
            for source in sources:
                if source in GENERATED:
                    (stage / source).write_text(backend_stub((stage / source).read_text()))
                    continue
                (stage / source).unlink()
                if source in STUBS:
                    shutil.copyfile(ROOT / STUBS[source], stage / source)
    (stage / 'build_profile.dyn').write_text(
        '// Generated by scripts/profile.py; do not edit.\n'
        f'const ProfileName: []const u8 = "{name}"\n'
        f'const ProfileKeymaps: []const u8 = "{" ".join(chosen["keymaps"])}"\n'
        f'const ProfileFrontends: []const u8 = "{" ".join(chosen["frontends"])}"\n'
        f'const ProfileExplorers: []const u8 = "{" ".join(chosen["explorers"])}"\n'
        f'const ProfilePickers: []const u8 = "{" ".join(chosen["pickers"])}"\n')
    deps = ROOT / 'build/deps'
    output = ROOT / 'build' / f'dna-{name}'
    # Link the bundled shared libraries whatever the caller's environment.
    environment = dict(os.environ, DYN_LIBRARY_PATH=str(deps / 'install/lib'))
    links = ['--link', str(deps / 'install/lib/libSDL3_ttf.so'), '--link', runpath()]
    if 'gui' not in chosen['frontends']:
        # Terminal only: the static native library built without SDL.
        environment['DYN_LIBRARY_PATH'] = str(deps / 'tui-static')
        links = []
    subprocess.run(['python3', str(ROOT / 'scripts/compile.py'), os.environ.get('DYN', 'dyn'), 'build', str(stage),
                    f'--{mode}', '--output', str(output), *links,
                    '--link', f'--version-script={deps / "hide-runtime.map"}'], check=True, env=environment)
    print(f'built {output} (profile {name}: ' + '; '.join(f'{slot} {", ".join(chosen[slot])}' for slot in SLOTS) + ')')


if __name__ == '__main__':
    main()
